options:
  string-option:
    type: string
    default: "Default Value"
    description: "A short description of the configuration option"
  boolean-option:
    type: boolean
    default: False
    description: "A short description of the configuration option"
  port:
    type: int
    default: 9092
    description: "The port that Kapacitor uses"

